name: "Install Prerequisites"

runs:
  using: "composite"
  steps:

    - name: Установка инструментов
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        build-essential \
        libgtest-dev \
        xutils-dev \
        cmake \
        clang clang-tidy

    - name: Установка Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
