name: "Make & Test"

on: [pull_request, push]

env:
  # На будущее, отсюда: https://github.com/vkats-spbu/HomeAssignments-spring-demo/blob/main/.github/workflows/cmake-single-platform.yml
  CMAKE_BUILD_TYPE: RelWithDebInfo

jobs:
  maketest:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        task: [ "00.DummyMake" ]

    steps:

    - name: Инсталляция инструментов
      uses: ./.github/actions/install-prerequisites

    - name: Получение кода
      uses: actions/checkout@v4

    - uses: ./.github/actions/make-utest
      with:
        exercise: ${{ matrix.task }}
